services:
  - type: web
    name: data-solution-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-api-key
      - key: PYTHON_VERSION
        value: 3.10.11